development:
  adapter: postgresql
  encoding: unicode
  database: level_zipcode_microservice 
  pool: 2
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>